version: 2
updates:
  - package-ecosystem: docker
    directory: '/docker/xserver'
    schedule:
      interval: daily
    open-pull-requests-limit: 2
    labels:
      - 'type: dependencies'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - 'type: dependencies'