version: '3'
services:
  pulseaudio:
    build: ./.docker/pulseaudio/Dockerfile
    container_name: pulseaudio_server
    networks:
      - audio_network

  ffmpeg:
    build: ./.docker/warp/Dockerfile
    container_name: warp_client
    depends_on:
      - pulseaudio
      - xserver
    networks:
      - audio_network
    volumes:
      - x11-socket:/tmp/.X11-unix
      - shared-data:/var/run/appconfig
    environment:
      PULSE_SERVER: "pulseaudio:4713"

  xserver:
    build: ./.docker/xserver/Dockerfile
    container_name: xserver
    volumes:
      - x11-socket:/tmp/.X11-unix
      - shared-data:/var/run/appconfig

networks:
  audio_network:
    driver: bridge
volumes:
  x11-socket:
    driver: local
  shared-data:
    driver: local