name: CI for .docker/pulseaudio

on:
  pull_request:
   paths:
    - ".docker/pulseaudio/**"
    - ".github/pulseaudio.yml"
  schedule:
    - cron: 0 0 * * * # At the end of everyday
  push:
    branches: [main]
    paths:
      - '.docker/pulseaudio/**'
      - ".github/pulseaudio.yml"
    tags:
      - v*.*.*
  release:
    types: [created]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: netrisme/netris
  BASE_TAG_PREFIX: pulseaudio

jobs:
  build-docker-pulseaudio-pr:
      name: Build pulseaudio image on pr
      runs-on: ubuntu-latest
      if: ${{ github.event_name == 'pull_request' }}
      steps:
        -
          name: Checkout repo
          uses: actions/checkout@v4
        - 
          name: Setup Docker Buildx
          uses: docker/setup-buildx-action@v3
        - 
          name: Build Docker image
          uses: docker/build-push-action@v5
          with:
            file: .docker/pulseaudio/Dockerfile
            context: .docker/pulseaudio
            push: false
            load: true
            tags: netris:pulseaudio

  build-docker-pulseudio-main:
      name: Build pulseaudio image on merge
      if: ${{github.ref == 'refs/heads/main'}}
      runs-on: ubuntu-latest
      permissions:
        contents: read
        packages: write
      steps:
        -
          name: Checkout repo
          uses: actions/checkout@v4
        - 
          name: Log into registry ${{ env.REGISTRY }}
          uses: docker/login-action@v3
          with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - 
          name: Extract Container metadata
          id: meta
          uses: docker/metadata-action@v5
          with:
            images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ env.BASE_TAG_PREFIX }}
            #
            #tag on release, and a nightly build for 'dev'
            tags: |
              type=raw,value=nightly,enable={{is_default_branch}}
              type=ref,event=tag
              type=semver,pattern={{version}}
              type=semver,pattern={{major}}.{{minor}}
              type=semver,pattern={{major}}
        - 
          name: Build Docker image
          uses: docker/build-push-action@v5
          with:
            file: .docker/pulseaudio/Dockerfile
            context: .docker/pulseaudio
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}